sudo: false
language: node_js
node_js:
- 10
script:
- npm rebuild node-sass
- NODE_ENV=production yarn build:dist
after_success:
- 'curl -L https://github.com/netlify/netlifyctl/releases/download/v0.1.0/netlifyctl-linux-amd64-v0.1.0.tar.gz | tar zx'
- '[ $TRAVIS_BRANCH == master ] && ./netlifyctl -y -A $NETLIFY_TOKEN -C netlify.prod.toml deploy'
- '[ $TRAVIS_BRANCH == release ] && ./netlifyctl -y -A $NETLIFY_TOKEN -C netlify.release.toml deploy'
branches:
  only:
    - master
    - release
notifications:
  slack:
    secure: nROAluwgT8ytE/2dlg2wKFDp/bA3AGd2SHOAN4mKwefAAyudofWhlx85qNLcLUAjfvIVYdPBRXx6BwlF0l5pAl7WCJKEFMAfhFZeXwEVd3DTXK9SvEwMym9qEiZXI6vyZY3IHb7MFy2p6uXpFE9Ub1Vdq8AEV7OPW8UZ742PYEA=
